/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASpace: typeof import('ant-design-vue/es')['Space']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
